version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    command: ["elasticsearch", "-Ecluster.routing.allocation.disk.threshold_enabled=false"]
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data17:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.16.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ENV=production
    volumes:
      - ollama_data:/data

  fastapi-app:
    build: ./fastapi-app
    container_name: fastapi-app
    depends_on:
      - elasticsearch
      - kibana
      - ollama
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-app:/app

volumes:
  elasticsearch-data17:
    driver: local
  ollama_data:
    driver: local
